name: mcChunkLoader
version: '1.0.2'
main: org.satellite.dev.progiple.mcchunkloader.McChunkLoader
api-version: '1.16'
authors: [ProGiple]
depend:
  - LunaSpring
  - NBTAPI
commands:
  mcchunkloader:
    usage: /mccl reload/give <player>
    aliases:
      - mccl
      - chunkloader
      - mcchunk
permissions:
  mcchunkloader.admin:
    default: op